[node]
name = "node-a.bunnymeshdb.test"
data_dir = "../../node-a/data"
listen = "127.0.0.1:8850"
p2p_listen = "9100"
worker_threads = 2
mesh_sync = true
sync_interval_secs = 30

[node.l3]
default_quota = 1048576

[[peers]]
name = "node-b.bunnymeshdb.test"
addr = "/ip4/127.0.0.1/tcp/9101"
pin = "f484b6616f388bb0bb69953c6f351bd5aed9abd9459c469c59b763e4731a17fd"
